Pages/UserShoppingCart/UserShoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using E85Carbs.WebServer.Helpers;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using E85Carbs.WebServer.Models;
using E85Carbs.WebServer.Services;
using E85Carbs.WebServer.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;

namespace E85Carbs.WebServer.Pages.UserShoppingCart
{
    [Authorize]
    public class UserShoppingCartModel : PageModel
    {
        [BindProperty]
        public string NormalizedUserName { get; set; }

        [BindProperty]
        public List<CartItem> CartItems { get; set; } = new List<CartItem> { };
        
        [BindProperty]
        public CartItem item { get; set; }
      
        public double Total { get; set; } = 0;

        public ShoppingCart shoppingCart { get; set; }

        [BindProperty]
        public CartItem cartItem { get; set; }

        private readonly ShoppingCartService _shoppingCartService;
        private readonly CartItemService _cartItemService;
        private readonly ProductService _productService;

        private readonly ILogger<UserShoppingCartModel> _logger;
        public ApplicationDbContext _context;

        public UserShoppingCartModel(ShoppingCartService shoppingCartService, CartItemService cartItemService, ILogger<UserShoppingCartModel> logger, ApplicationDbContext context, ProductService productService)
        {
            _shoppingCartService = shoppingCartService;
            _cartItemService = cartItemService;
            _productService = productService;
            _logger = logger;
            _context = context;

        }
        public IActionResult OnGet()
        {
           
          ShoppingCart ThisCart = _shoppingCartService.GetAShoppingCart(User.Identity.Name);
            if(ThisCart != null)
            {
                CartItems = ThisCart.CartItems;
                
                foreach(var item in CartItems)
                {
                    Total = Total + (item.Product.ProductPrice * item.Quantity);

                }
            }
          
           
            return Page();            
        }
        
        public IActionResult OnPost(int id)
        {
            ShoppingCart currentCart = _shoppingCartService.GetAShoppingCart(User.Identity.Name);
            CartItem cartItem = _cartItemService.GetACartItemByProductId(id);
            if (currentCart != null && cartItem != null)
            {
                _cartItemService.UpdateAdd1(id);
                return RedirectToPage("/UserShoppingCart/UserShoppingCart");
            }

            else if(currentCart == null)
            {
                currentCart = new ShoppingCart
                {
                   
                    DateCreated = System.DateTime.Now,
                    NormalizedUserName = User.Identity.Name,
                    CartItems = CartItems

                };
                CartItem newCartItem = new CartItem
                {
                    ProductId = id,
                    Quantity = 1,
                    DateCreated = System.DateTime.Now
                };
                
                currentCart.CartItems.Add(newCartItem);
                _shoppingCartService.AddNewShoppingCart(currentCart);
            }            
            else
            {
                
                CartItem newCartItem = new CartItem
                {
                    ProductId = id,
                    Quantity = 1,
                    DateCreated = System.DateTime.Now,
                    ShoppingCartId = currentCart.ShoppingCartId
                   
                };
                _cartItemService.AddNewCartItem(newCartItem);
                
            }

            return RedirectToPage("/UserShoppingCart/UserShoppingCart");
        }



        public IActionResult OnGetDeleteFromCart(int deleteid)
        {
            _cartItemService.DeleteACartItem(deleteid);
            return RedirectToPage("/UserShoppingCart/UserShoppingCart");
        }

        public IActionResult OnPostUpdateCartItem()
        {
            if(item.Quantity > 1)
            {
                _cartItemService.UpdateQuantity(item.CartItemId, item.Quantity);
                return RedirectToPage("/UserShoppingCart/UserShoppingCart");

            }
            else
            {
                _cartItemService.DeleteACartItem(item.CartItemId);
               
                return RedirectToPage("/UserShoppingCart/UserShoppingCart");
            }                        
        }
    }
}

Pages/UserShoppingCart/UserShoppingCart.cshtml
@page 
@model E85Carbs.WebServer.Pages.UserShoppingCart.UserShoppingCartModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
}



<section class="clean-block clean-cart dark">
    <div class=" container">
        <div class="block-heading">
            <h2 class="text-info">Shopping Cart</h2>
        </div>
        <div class="content">
            <div class="row no-gutters">
                <div class="col-md-12 col-lg-8">
                    <div class="items">          
                        @foreach (var item in Model.CartItems)
                        {
                            <div class="product">
                                <div class=" row justify-content-center align-items-center">
                                    <div class="col-md-2 remove"><a asp-page="/UserShoppingCart/UserShoppingCart" asp-page-handler="DeleteFromCart" asp-route-deleteid="@item.CartItemId">X</a></div>
                                    <div class="col-md-3">
                                        <div class="product-image"><img class="img-fluid d-block mx-auto image" src="data:image/gif;base64,@item.Product.MainBase64Image" /></div>
                                    </div>
                                    <div class="col-md-5 pruduct-info">
                                        <a class="product-name" href="#">@item.Product.ProductName</a>
                                    </div>
                                    <div class="col-6 col-md-2 quantity">
                                        <form method="post" asp-page-handler="UpdateCartItem">
                                            <input type="number" value="@item.Quantity" asp-for="@item.Quantity" class="form-control" />
                                            <input type="hidden" asp-for="@item.CartItemId" />
                                       @*item is bound in cs to match item variable*@
                                        </form>
                                    </div>
                                    <div class="col-6 col-md-2 price"><span> $@(item.Product.ProductPrice * item.Quantity )</span></div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div class="col-md-12 col-lg-4">
                    <div class="summary">
                        <h3>Summary</h3>
                        <h4><span class="text">Subtotal</span><span class="price">$@Model.Total</span></h4>
                        <h4><span class="text">Discount</span><span class="price">$0</span></h4>
                        <h4><span class="text">Shipping</span><span class="price">$0</span></h4>
                        <h4><span class="text">Total</span><span class="price">$@Model.Total</span></h4>
                    </div>
                    <!--<div>
                        <div id="paypal-button-container"></div>-->

                        <!-- Include the PayPal JavaScript SDK -->
                        <!--<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>

                        <script>
                            // Render the PayPal button into #paypal-button-container
                            paypal.Buttons({

                                // Set up the transaction
                                createOrder: function (data, actions) {
                                    return actions.order.create({
                                        purchase_units: [{
                                            amount: {
                                                value: '88.44'
                                            }
                                        }]
                                    });
                                },

                                // Finalize the transaction
                                onApprove: function (data, actions) {
                                    return actions.order.capture().then(function (orderData) {
                                        // Successful capture! For demo purposes:
                                        console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                                        var transaction = orderData.purchase_units[0].payments.captures[0];
                                        alert('Transaction ' + transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

                                        // Replace the above to show a success message within this page, e.g.
                                        // const element = document.getElementById('paypal-button-container');
                                        // element.innerHTML = '';
                                        // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                                        // Or go to another URL:  actions.redirect('thank_you.html');
                                    });
                                }


                            }).render('#paypal-button-container');
                        </script>
                    </div>-->
                </div>
            </div>
        </div>
    </div>
</section>

<div>
    <a type="button" asp-page="/UserStore/UserStoreMainPage" class="btn btn-info">Continue Shopping</a>
</div>